default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost


development:
  <<: *default
  database: ecommercedb

test:
  <<: *default
  database: ecommercedb_test


production:
  primary: &primary_production
    <<: *default
    database: ecommerce_app_production
    username: ecommerce_app
    password: <%= ENV["ECOMMERCE_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ecommerce_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ecommerce_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ecommerce_app_production_cable
    migrations_paths: db/cable_migrate
